---
- name: Ensure SSH daemon is running.
  service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_sshd_state }}"

- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
    state: present
    validate: 'sshd -T -f %s'
    mode: 0644
  with_items:
    - regexp: '^PasswordAuthentication'
      insertafter: '^#PasswordAuthentication'
      line: "PasswordAuthentication {{ security_ssh_password_authentication }}"
    - regexp: '^PermitRootLogin'
      insertafter: '^#PermitRootLogin'
      line: "PermitRootLogin {{ security_ssh_permit_root_login }}"
    - regexp: '^Port'
      insertafter: '^#Port'
      line: "Port {{ security_ssh_port }}"
    - regexp: '^UseDNS'
      insertafter: '^#UseDNS'
      line: "UseDNS {{ security_ssh_usedns }}"
    - regexp: '^PermitEmptyPasswords'
      insertafter: '^#PermitEmptyPasswords'
      line: "PermitEmptyPasswords {{ security_ssh_permit_empty_password }}"
    - regexp: '^ChallengeResponseAuthentication'
      insertafter: '^#ChallengeResponseAuthentication'
      line: "ChallengeResponseAuthentication {{ security_ssh_challenge_response_auth }}"
    - regexp: '^GSSAPIAuthentication'
      insertafter: '^#GSSAPIAuthentication'
      line: "GSSAPIAuthentication {{ security_ssh_gss_api_authentication }}"
    - regexp: '^X11Forwarding'
      insertafter: '^#X11Forwarding'
      line: "X11Forwarding {{ security_ssh_x11_forwarding }}"
  notify: restart ssh

- name: Add configured users allowed to connect over ssh
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: '^AllowUsers'
    insertafter: '^#AllowUsers'
    line: "AllowUsers {{ security_ssh_allowed_users | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: security_ssh_allowed_users | length > 0
  notify: restart ssh

- name: Add configured groups allowed to connect over ssh
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: '^AllowGroups'
    insertafter: '^#AllowGroups'
    line: "AllowGroups {{ security_ssh_allowed_groups | join(' ') }}"
    state: present
    create: true
    validate: 'sshd -T -f %s'
    mode: 0644
  when: security_ssh_allowed_groups | length > 0
  notify: restart ssh

- name: Add configured user accounts to passwordless sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ security_sudoers_passwordless }}"
  when: security_sudoers_passwordless | length > 0

- name: Add configured user accounts to passworded sudoers.
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ security_sudoers_passworded }}"
  when: security_sudoers_passworded | length > 0
